server:
  port: 10500

spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/spring-boot-jpa-sample1"
    username: postgres
    password: postgres
  zipkin:
    enabled: false
